apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jrmwfa2kl-nodejs 
  janus-idp.io/tekton: jrmwfa2kl-nodejs
  backstage.io/kubernetes-id: jrmwfa2kl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jrmwfa2kl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  